### ISSUE TITLE
为什么TCP server接收比较小的TCP数据包时会丢弃呢？

### ISSUE THREAD

**Issue by demon-iak** [gaochundong/Cowboy#1]
不论是tap还是APM方式都是这样。

**Comment by demon-iak** [comment]
原来之前默认用的是FixedLengthFrameBuilder，改成RawBufferFrameBuilder就好了

**Comment by gaochundong** [comment]
感谢 @demon-iak 提出了第一个Issue并自己Fixed了。
RawBufferFrameBuilder 用起来很随意，小包数量少时没问题，还是推荐有包头的 Builder。
