### ISSUE TITLE
Exception "Cannot access a disposed object." when exiting from Cowboy.Sockets.TestAsyncTcpSocketClient

### ISSUE THREAD

**Issue by hzeng-tfs** [gaochundong/Cowboy#5]
Thanks for sharing your code.

Just want to report an issue. 
When I run the test code for Cowboy.Sockets.TestAsyncTcpSocketClient. All good until I typed "quit" to exit from EXE file.
Thanks.

Here is the printout from Visual Studio 2017.

_2017-05-30 16:25:20.2846|DEBUG|Cowboy.Sockets.AsyncTcpSocketClient|Connected to server [127.0.0.1:22222] with dispatcher
 [SimpleMessageDispatcher] on [2017-05-30 06:55:20.2706152].
TCP server 127.0.0.1:22222 has connected.
TCP client has connected to server [127.0.0.1:22222].
Type something to send to server...
**hello**
Client [127.0.0.1:23619] send text -> [5 Bytes].
Server : 127.0.0.1:22222 --> hello
**quit**
2017-05-30 16:25:30.3226|DEBUG|Cowboy.Sockets.AsyncTcpSocketClient|Disconnected from server [127.0.0.1:22222] with dispatcher [SimpleMessageDispatcher] on [2017-05-30 06:55:30.3226203].
TCP server 127.0.0.1:22222 has disconnected.
TCP client has disconnected from server [127.0.0.1:22222]._
```
2017-05-30 16:25:30.3486|ERROR|Cowboy.Sockets.AsyncTcpSocketClient|Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.

Exception Details:
--------------------------------------
Exception Type: System.ObjectDisposedException
Message: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
ObjectName: System.Net.Sockets.NetworkStream
TargetSite: Int32 EndRead(System.IAsyncResult)
HelpLink: NULL
Source: System

Exception StackTrace:
--------------------------------------
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Cowboy.Sockets.AsyncTcpSocketClient.<Process>d__36.MoveNext() in D:\Downloads\sourcecode\Cowboy-master\Cowboy\Cowboy.Sockets\Tcp\Client\TAP\AsyncTcpSocketClient.cs:line 260
```

**Comment by gaochundong** [comment]
Thank you for you report, and the issue has been resolved.

**Comment by hzeng-tfs** [comment]
Hi Dennis,
thanks for your updates.
I noticed that you had added code to catch the exception. However the exception is still there.

I had done some research on this issue and I think I have found a solution.

on `Program.cs` of `Cowboy.Sockets.TestAsyncTcpSocketClient` project
calls a new method `Shutdown()` instead of calling `Close()`
```
                //_client.Close().Wait();
                _client.Shutdown();

```
Adds method `Shutdown()` to `AsyncTcpSocketclients.cs` of `Cowboy.Sockets.TestAsyncTcpSocketClient` project

```
        public void Shutdown()
        {
            _tcpClient.Client.Shutdown(SocketShutdown.Send);
        }
```

What is happening is that:
- you type "quit" on client side
- client calls Shutdown() which notifies server that client wants to disconnect.
- Server returns with a 0-byte packet indicating server is ready to disconnect
- Process() detects 0-byte packet and then close and dispose.
```
0x45FC, Worker Thread, receiveCount=6
0x3A40, Main Thread, _tcpClient.Client.Shutdown
0x45FC, Worker Thread, receiveCount=0
0x45FC, Worker Thread, Close() in Process()
0x45FC, Worker Thread, _stream.Dispose();
0x45FC, Worker Thread, _tcpClient.Close();
OnServerDisconnected
```
for more information see: [this on stackoverflow](https://stackoverflow.com/a/28485243)

However, interestingly, only the TAP client test code has this issue. The APM and SAEA client test code don't. Maybe it is something to do with `async` and `await`?

Things may become more complicated if server doesn't following above good behaviours, i.e. returning a 0-byte packet. :(

**Comment by gaochundong** [comment]
@hzeng-tfs Great finding and thanks for your detail analysis.
I just improved the Close method to issue a Send shutdown notification to let the tcp channel receives a 0-byte, and that works gracefully. Please kindly have a review about it.

**Comment by gaochundong** [comment]
Then, finally, introduce and expose the Shutdown() method as public, so both the Close() and the Shutdown() can be used in user-side to determine whether need a graceful close.

Please kindly have a review about this implementation if you get free, thanks a lot.

**Comment by hzeng-tfs** [comment]
That sounds good to me. :)
