### ISSUE TITLE
如果要遍历整个TcpSocketSaeaServer的session，怎么做？或者我要主动踢掉某个session呢？

### ISSUE THREAD

**Issue by tianjun9** [gaochundong/Cowboy#6]
首先，感谢共享这个项目代码。
有几个问题：如果要遍历整个TcpSocketSaeaServer的session，怎么做？或者我要主动踢掉某个session呢？望答复，不胜感谢。

**Comment by gaochundong** [comment]
每一个Session有一个唯一的SessionKey作为其主键，Session归Server管理，所以 Server 中包含 HasSession, GetSession, CloseSession 三个方法用于操作 Session。请参考。

**Comment by tianjun9** [comment]
感谢你的回复，我把TcpSocketSaeaServer的_sessions改成public的了   :+1:

**Comment by gaochundong** [comment]
通过订阅Event可以接收到Session建立的通知，在外部是可以收集到Session列表的。
另，使用源代码编译显然是没有问题的，方便起见也可以直接使用 nuget 包进行引用。

**Comment by tianjun9** [comment]
所以，我一定要通过OnSessionStarted事件中去保存到我的session列表，然后OnSessionClosed中从我自己的session列表中删除掉呢！如果能把TcpSocketSaeaServer的_sessions通过接口暴露出来就更好了，这样，我就可以直接使用 nuget 包进行引用了，而不用像现在只能吧源代码包含到我的编译工程里去[捂脸][捂脸][捂脸]

**Comment by gaochundong** [comment]
踢Session肯定是业务的要求，也就是说 SessionID 一定会映射到一个业务模型，例如一个用户连接的UserID，踢掉该User，则Close该UserID对应的Session。如果是这样，Session也是必须要收集的啊。

**Comment by tianjun9** [comment]
我决定听你的，搜集session来维护自己的list。因为，我确实遇到你说的这一种应用需求了。。。之前只是因为在学习使用这个lib，所以没有考虑到这么多。。。非常感谢！

**Comment by tianjun9** [comment]
再问两个问题：
1、Logrila.Logging这个东西怎么用的？
2、大多数，我使用LineBasedFrameBuilder来接受基于行0x0d 0x0a的报文。但，有时候一次的传输并没有行结尾标志，而我又想把报文收过来，该怎么办呢？

**Comment by gaochundong** [comment]
1. Logrila 的存在，是为了解决多种 Log 框架的依赖问题。有的应用使用 log4net，有的使用 NLog，还有 Serilog 等，但不能将某一框架绑定到 Cowboy/Redola 类库中，所以，让 Cowboy/Redola 仅依赖 Logrila 这个中间层，Logrila 仅是通用 Log 的一层抽象，具体应用层使用何种框架并不是 Cowboy/Redola 关心的。

2. 一次传输，并没有结尾标志？？这实际上涉及到通信协议的设计，LineBased 就是一种约定设计，使用换行符做包分割。所以，Socket 通信双发必须有个约定，双方发什么消息格式。如果不约定，那就是碰运气，Cowboy 中也有这种支持，RawBufferFrameBuilder，参考下。
