### ISSUE TITLE
我只想说你的英文注释看的好累

### ISSUE THREAD

**Issue by liu343536** [gaochundong/Cowboy#7]
跛脚的“中国式英语”，你不说我也知道你是中国人。还以是相对成熟的封装，研究了半天发现不适用我的项目，浪费时间

**Comment by gaochundong** [comment]
服。

1. 我是中国人，就不能用跛脚英语写注释吗？我的风格是尽量不写注释的，所以你能看注释看到累也是厉害了。
2. APM 很成熟，我在生产环境使用 1 年多了。其他，TAP/SAEA/RIO，我并没有在生产环境使用，至于成不成熟，你开心就好。
3. 开源个代码，就是为你的项目倾心设计的吗？谁知道你要实现什么功能？我猜你也是靠 百度搜索 搜到的这个框架吧，关键字是 TCP Socket 吧？证明你基本上是不懂 Socket 的菜鸟啊。
4. 我是好心人，推荐你使用 `[SuperSocket](http://www.supersocket.net/)` ，很成熟的框架，只是担心你看不懂代码。

Thanks,
Dennis
