### ISSUE TITLE
关于AsyncTcpSocketSession.cs中的SendAsync方法的疑问

### ISSUE THREAD

**Issue by huiliu** [gaochundong/Cowboy#8]
如果有多个线程同时调用SendAsync，即多个线程同时向同一个stream中写入数据，好像没有处理，这样不会导致问题吗？
[AsyncTcpSocketSession.cs](https://github.com/gaochundong/Cowboy/blob/master/Cowboy/Cowboy.Sockets/Tcp/Server/TAP/AsyncTcpSocketSession.cs)

**Comment by gaochundong** [comment]
@huiliu 

是的，BeginSend, SendAsync 方法本身不是 thread-safe 的，但将其变成 thread-safe 可在不同的位置进行处理，可在 Framework 内处理，也可在 Application 也就是调用方处理。 

Cowboy 当前的代码是没有进行这种处理的，这本身是因为 Cowboy 是建立在 TcpListener/TcpClient 上的一层封装，而 TcpListener/TcpClient 默认也是没有进行 thread-safe 处理。

如果加 thread-safe 处理，可选方案：
1. 使用 lock，socket 同一时间仅允许 1 个线程进行操作 send/write；这将演变成阻塞操作；
2. 使用 queue，send 接口将调用的内容 push 到一个 send-queue 中，使用单独的 1 个线程处理 queue 顺序处理。这样不阻塞发送端，queue 增加了复杂度。

上述方案，感觉都不是很理想，如有更好的办法，请分享，谢谢。

Thanks,
Dennis

**Comment by huiliu** [comment]
@gaochundong 谢谢！

因为我的代码中有thread-safe的问题，所以使用了一个缓存队列，当异步操作没有完成前，先将数据放入到队列中，异步操作完成后，检查队列是否为空，如果不为空则将队列数据取出来发送，在队列清空之前，新的数据只能写入到队列中。
