### ISSUE TITLE
连续发送，服务端没有收到消息

### ISSUE THREAD

**Issue by langxw** [gaochundong/Cowboy#9]
@gaochundong 
我使用EAP方式做的服务端，使用RawBufferFrameBuilder来接收数据，做的一个简单的Websocket Server，当Chrome中连续发送数据的时候，服务端
`public async Task OnSessionDataReceived(TcpSocketSaeaSession session, byte[] data, int offset, int count)`
方法只收到前两次事件，后面的都没有收到，请问这个是什么情况，可以解决吗？
Javascript里面的方法是这样的
`        function sendMu() {

            message.sendMessage('dal', 'shop_query', '');

            var sendJson = {};
            sendJson.whereField = 'ProductType';
            sendJson.whereValue = 0;
            var str = JSON.stringify(sendJson);
            message.sendMessage('dal', 'product_query', str);

            sendJson = {};
            sendJson.whereField = 'DepartmentName';
            sendJson.whereValue = '会籍部';
            var str = JSON.stringify(sendJson);
            message.sendMessage('dal', 'employee_query', str);
        }`

**Comment by gaochundong** [comment]
Hi，

请尽量不要使用 RawBufferFrameBuilder ，它存在的目的是为了进行测试，与其他框架的互通等，特点是没有封装包头的裸数据，正是因为是裸数据，会在使用中出现无法判断数据长度和接收数据混乱等问题。

请选择使用其他类型的FrameBuilder，通常推荐选择带数据包头部定义的，例如 [LengthPrefixedFrameBuilder](https://github.com/gaochundong/Cowboy/blob/master/Cowboy/Cowboy.Sockets/Tcp/Framing/LengthPrefixedFrameBuilder.cs) 等。

如果你看了 WebSocket 协议的 [RFC](https://www.rfc-editor.org/rfc/rfc6455.txt) 定义，其中详细描述了 FrameBuilder 类似的数据包头部格式定义，原理是类似的。
`5.2.  Base Framing Protocol

   This wire format for the data transfer part is described by the ABNF
   [RFC5234] given in detail in this section.  (Note that, unlike in
   other sections of this document, the ABNF in this section is
   operating on groups of bits.  The length of each group of bits is
   indicated in a comment.  When encoded on the wire, the most
   significant bit is the leftmost in the ABNF).  A high-level overview
   of the framing is given in the following figure.  In a case of
   conflict between the figure below and the ABNF specified later in
   this section, the figure is authoritative.

      0                   1                   2                   3
      0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
     +-+-+-+-+-------+-+-------------+-------------------------------+
     |F|R|R|R| opcode|M| Payload len |    Extended payload length    |
     |I|S|S|S|  (4)  |A|     (7)     |             (16/64)           |
     |N|V|V|V|       |S|             |   (if payload len==126/127)   |
     | |1|2|3|       |K|             |                               |
     +-+-+-+-+-------+-+-------------+ - - - - - - - - - - - - - - - +
     |     Extended payload length continued, if payload len == 127  |
     + - - - - - - - - - - - - - - - +-------------------------------+
     |                               |Masking-key, if MASK set to 1  |
     +-------------------------------+-------------------------------+
     | Masking-key (continued)       |          Payload Data         |
     +-------------------------------- - - - - - - - - - - - - - - - +
     :                     Payload Data continued ...                :
     + - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
     |                     Payload Data continued ...                |
     +---------------------------------------------------------------+`

WebSocket Server，请直接参考使用 [Cowboy.WebSockets](https://github.com/gaochundong/Cowboy.WebSockets) 即可，也是通过 EAP 模式实现的。

Thanks,
Dennis

**Comment by langxw** [comment]
谢谢回答。
是不是因为没有封包的原因导致的消息丢失？
我测试下来不管有没有封包或者不可读的包都没有收到信息的。
